// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa9eKpTYMSsrHfdic_qOnJ1iDgR9yTN5c',
    appId: '1:560768402536:web:35c51f00eb6359d9f9e7dd',
    messagingSenderId: '560768402536',
    projectId: 'takeit-939c9',
    authDomain: 'takeit-939c9.firebaseapp.com',
    storageBucket: 'takeit-939c9.firebasestorage.app',
    measurementId: 'G-RYNFCEGLJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDykC7w_umrJhMawGZxEyGED7Yx5O8eI1g',
    appId: '1:560768402536:android:70ee554bb5265568f9e7dd',
    messagingSenderId: '560768402536',
    projectId: 'takeit-939c9',
    storageBucket: 'takeit-939c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3AWmk_Zvb3BLsmbcbwSYFjjigDAPACaU',
    appId: '1:560768402536:ios:fc85142baadc527ff9e7dd',
    messagingSenderId: '560768402536',
    projectId: 'takeit-939c9',
    storageBucket: 'takeit-939c9.firebasestorage.app',
    iosBundleId: 'com.example.takeit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3AWmk_Zvb3BLsmbcbwSYFjjigDAPACaU',
    appId: '1:560768402536:ios:fc85142baadc527ff9e7dd',
    messagingSenderId: '560768402536',
    projectId: 'takeit-939c9',
    storageBucket: 'takeit-939c9.firebasestorage.app',
    iosBundleId: 'com.example.takeit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa9eKpTYMSsrHfdic_qOnJ1iDgR9yTN5c',
    appId: '1:560768402536:web:be07da575585fbcaf9e7dd',
    messagingSenderId: '560768402536',
    projectId: 'takeit-939c9',
    authDomain: 'takeit-939c9.firebaseapp.com',
    storageBucket: 'takeit-939c9.firebasestorage.app',
    measurementId: 'G-23P6BPXDNH',
  );
}
